/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author YAHYA
 */
public class Awal extends javax.swing.JFrame {

    /**
     * Creates new form Awal
     */
    public Awal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        antrean = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        customerService = new javax.swing.JButton();
        teller = new javax.swing.JButton();
        BACKGROUND = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        antrean.setText("Antrean");
        getContentPane().add(antrean, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 10, -1, -1));

        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        customerService.setBackground(new java.awt.Color(0, 102, 204));
        customerService.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 48)); // NOI18N
        customerService.setForeground(new java.awt.Color(255, 255, 255));
        customerService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/31.jpg"))); // NOI18N
        customerService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerServiceActionPerformed(evt);
            }
        });
        getContentPane().add(customerService, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 230, 150));

        teller.setBackground(new java.awt.Color(51, 153, 255));
        teller.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 48)); // NOI18N
        teller.setForeground(new java.awt.Color(255, 255, 255));
        teller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/32.jpg"))); // NOI18N
        teller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tellerActionPerformed(evt);
            }
        });
        getContentPane().add(teller, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 210, 150));

        BACKGROUND.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/7.jpg"))); // NOI18N
        BACKGROUND.setText(" ");
        getContentPane().add(BACKGROUND, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerServiceActionPerformed
      
    }//GEN-LAST:event_customerServiceActionPerformed

    private void tellerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tellerActionPerformed
      
    }//GEN-LAST:event_tellerActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
      
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Awal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Awal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BACKGROUND;
    private javax.swing.JButton antrean;
    private javax.swing.JButton bLogin;
    private javax.swing.JButton customerService;
    private javax.swing.JButton teller;
    // End of variables declaration//GEN-END:variables

    public JButton getCustomerService() {
        return customerService;
    }

    public void setCustomerService(JButton customerService) {
        this.customerService = customerService;
    }

    public JButton getTeller() {
        return teller;
    }

    public void setTeller(JButton teller) {
        this.teller = teller;
    }
    
        public void addActionListener(ActionListener x) {
        bLogin.addActionListener(x);
        customerService.addActionListener(x);
        teller.addActionListener(x);
        antrean.addActionListener(x);
    }

    public JButton getbLogin() {
        return bLogin;
    }

    public JButton getAntrean() {
        return antrean;
    }

    public void setAntrean(JButton antrean) {
        this.antrean = antrean;
    }
    
    
    


    
}
