/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author YAHYA
 */
public class viewUpgradeKartu extends javax.swing.JFrame {

    /**
     * Creates new form viewUpgradeKartu
     */
    public viewUpgradeKartu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noKartu = new javax.swing.JTextField();
        jenisAwalKartu = new javax.swing.JComboBox<>();
        upgradeKe = new javax.swing.JComboBox<>();
        Batal = new javax.swing.JButton();
        OK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noKartuActionPerformed(evt);
            }
        });
        getContentPane().add(noKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 250, 40));

        jenisAwalKartu.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jenisAwalKartu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATMBiasa", "debitSilver", "debitGold", "debitPlatinum" }));
        getContentPane().add(jenisAwalKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 150, 40));

        upgradeKe.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        upgradeKe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ATMBiasa", "debitSilver", "debitGold", "debitPlatinum" }));
        getContentPane().add(upgradeKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 150, 40));

        Batal.setText("Batal");
        getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 80, -1));

        OK.setText("OK");
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 590, 80, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/15.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 938, 664));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noKartuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noKartuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewUpgradeKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewUpgradeKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewUpgradeKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewUpgradeKartu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewUpgradeKartu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JButton OK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> jenisAwalKartu;
    private javax.swing.JTextField noKartu;
    private javax.swing.JComboBox<String> upgradeKe;
    // End of variables declaration//GEN-END:variables

    public void addActionListener(ActionListener x) {
        Batal.addActionListener(x);
        OK.addActionListener(x);
    }

    public String getJenisAwalKartu() {
        return jenisAwalKartu.getItemAt(jenisAwalKartu.getSelectedIndex());
    }



    public String getNoKartu() {
        return noKartu.getText();
    }
    public String getUpgradeKe() {
        return upgradeKe.getItemAt(upgradeKe.getSelectedIndex());
    }

    public JButton getBatal() {
        return Batal;
    }

    public void setBatal(JButton Batal) {
        this.Batal = Batal;
    }

    public JButton getOK() {
        return OK;
    }

    public void setOK(JButton OK) {
        this.OK = OK;
    }
    
    
    
}
