/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author YAHYA
 */
public class viewTeller extends javax.swing.JFrame {

    /**
     * Creates new form viewTeller
     */
    public viewTeller() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setorTarik = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setorTarik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/33.jpg"))); // NOI18N
        setorTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorTarikActionPerformed(evt);
            }
        });
        getContentPane().add(setorTarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 570, 150));

        transfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/35.jpg"))); // NOI18N
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        getContentPane().add(transfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 560, 560, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/8.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -27, 1180, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setorTarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorTarikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_setorTarikActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed

    }//GEN-LAST:event_transferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewTeller.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewTeller().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton setorTarik;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
public JButton getSetorTarik() {
        return setorTarik;
    }

    public void setSetorTarik(JButton setorTarik) {
        this.setorTarik = setorTarik;
    }

    public JButton getTransfer() {
        return transfer;
    }

    public void setTransfer(JButton transfer) {
        this.transfer = transfer;
    }
    public void addActionListener(ActionListener x) {
        setorTarik.addActionListener(x);
        transfer.addActionListener(x);
    }
    
    






}
