/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import java.util.Date;

/**
 *
 * @author YAHYA
 */
public class viewCustomerService extends javax.swing.JFrame {

    /**
     * Creates new form viewCustomerService
     */
    public viewCustomerService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tahun = new javax.swing.JComboBox<>();
        tanggal = new javax.swing.JComboBox<>();
        bulan = new javax.swing.JComboBox<>();
        pendidikanTerakhir = new javax.swing.JTextField();
        noRekening = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        noTelepon = new javax.swing.JTextField();
        namaWali = new javax.swing.JTextField();
        namaLengkap = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tahun", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "" }));
        getContentPane().add(tahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 70, 30));

        tanggal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tanggal", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 70, 30));

        bulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "bulan", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        bulan.setToolTipText("");
        getContentPane().add(bulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 70, 30));
        getContentPane().add(pendidikanTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 580, 270, 30));
        getContentPane().add(noRekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, 270, 30));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 480, 270, 30));
        getContentPane().add(noTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, 270, 30));
        getContentPane().add(namaWali, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 270, 30));
        getContentPane().add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 310, 270, 30));
        getContentPane().add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 270, 30));

        ok.setText("OK");
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 620, 60, 40));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 620, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/12.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed

    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCustomerService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton batal;
    private javax.swing.JComboBox<String> bulan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JTextField namaWali;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField noRekening;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JButton ok;
    private javax.swing.JTextField pendidikanTerakhir;
    private javax.swing.JComboBox<String> tahun;
    private javax.swing.JComboBox<String> tanggal;
    // End of variables declaration//GEN-END:variables

    public String getAlamat() {
        return alamat.getText();
    }

    public void setAlamat(JTextField alamat) {
        this.alamat = alamat;
    }

    public JButton getBatal() {
        return batal;
    }

    public void setBatal(JButton batal) {
        this.batal = batal;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public String getNamaLengkap() {
        return namaLengkap.getText();
    }

    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap.setText(namaLengkap);
    }

    public String getNik() {
        return nik.getText();
    }

    public void setNik(String nik) {
        this.nik.setText(nik);
    }

    public String getNoRekening() {
        return noRekening.getText();
    }

    public void setNoRekening(String noRekening) {
        this.noRekening.setText(noRekening);
    }

    public String getNoTelepon() {
        return noTelepon.getText();
    }

    public void setNoTelepon(String noTelepon) {
        this.noTelepon.setText(noTelepon);
    }

    public String getPendidikanTerakhir() {
        return pendidikanTerakhir.getText();
    }

    public void setPendidikanTerakhir(String pendidikanTerakhir) {
        this.pendidikanTerakhir.setText(pendidikanTerakhir);
    }

    public void addActionListener(ActionListener x) {
        ok.addActionListener(x);
        batal.addActionListener(x);
        tahun.addActionListener(x);
        tanggal.addActionListener(x);
        bulan.addActionListener(x);
        
    }

    public String getNamaWali() {
        return namaWali.getText();
    }

    public JButton getOk() {
        return ok;
    }
    public String getDate() {

        String t=tahun.getItemAt(tahun.getSelectedIndex())+"-"+bulan.getSelectedIndex()+"-"+tanggal.getSelectedIndex();
        return t;
        
    }
    
    
    
    
}
