/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author YAHYA
 */
public class viewPilihanCS extends javax.swing.JFrame {

    /**
     * Creates new form viewPilihanCS
     */
    public viewPilihanCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bukaRekening = new javax.swing.JButton();
        upgrade = new javax.swing.JButton();
        lainlain = new javax.swing.JButton();
        laporanKehilangan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bukaRekening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/43.jpg"))); // NOI18N
        bukaRekening.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(bukaRekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 720, 80));

        upgrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/44.jpg"))); // NOI18N
        upgrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upgradeActionPerformed(evt);
            }
        });
        getContentPane().add(upgrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 720, 80));

        lainlain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/46.jpg"))); // NOI18N
        getContentPane().add(lainlain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 720, 80));

        laporanKehilangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/45.jpg"))); // NOI18N
        getContentPane().add(laporanKehilangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 720, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/47.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upgradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upgradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upgradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewPilihanCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewPilihanCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewPilihanCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPilihanCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewPilihanCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bukaRekening;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton lainlain;
    private javax.swing.JButton laporanKehilangan;
    private javax.swing.JButton upgrade;
    // End of variables declaration//GEN-END:variables

    public JButton getBukaRekening() {
        return bukaRekening;
    }

    public void setBukaRekening(JButton bukaRekening) {
        this.bukaRekening = bukaRekening;
    }

    public JButton getLainlain() {
        return lainlain;
    }

    public void setLainlain(JButton lainlain) {
        this.lainlain = lainlain;
    }

    public JButton getLaporanKehilangan() {
        return laporanKehilangan;
    }

    public void setLaporanKehilangan(JButton laporanKehilangan) {
        this.laporanKehilangan = laporanKehilangan;
    }

    public JButton getUpgrade() {
        return upgrade;
    }

    public void setUpgrade(JButton upgrade) {
        this.upgrade = upgrade;
    }
    public void addActionListener(ActionListener x) {
        bukaRekening.addActionListener(x);
        lainlain.addActionListener(x);
        laporanKehilangan.addActionListener(x);
        upgrade.addActionListener(x);
    }

   
}
