/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author YAHYA
 */
public class viewCustomerService extends javax.swing.JFrame {

    /**
     * Creates new form viewCustomerService
     */
    public viewCustomerService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pendidikanTerakhir = new javax.swing.JTextField();
        noRekening = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        noTelepon = new javax.swing.JTextField();
        tglLahir = new javax.swing.JTextField();
        namaWali = new javax.swing.JTextField();
        namaLengkap = new javax.swing.JTextField();
        nik = new javax.swing.JTextField();
        ok = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(pendidikanTerakhir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 540, 270, 30));
        getContentPane().add(noRekening, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 270, 30));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, 270, 30));
        getContentPane().add(noTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 270, 30));
        getContentPane().add(tglLahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 270, 30));
        getContentPane().add(namaWali, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 270, 30));
        getContentPane().add(namaLengkap, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 270, 30));
        getContentPane().add(nik, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 270, 30));

        ok.setText("OK");
        getContentPane().add(ok, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, 60, 40));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 590, 80, 40));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
       Awal awal=new Awal();
       awal.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCustomerService().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alamat;
    private javax.swing.JButton batal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField namaLengkap;
    private javax.swing.JTextField namaWali;
    private javax.swing.JTextField nik;
    private javax.swing.JTextField noRekening;
    private javax.swing.JTextField noTelepon;
    private javax.swing.JButton ok;
    private javax.swing.JTextField pendidikanTerakhir;
    private javax.swing.JTextField tglLahir;
    // End of variables declaration//GEN-END:variables

    public JTextField getAlamat() {
        return alamat;
    }

    public void setAlamat(JTextField alamat) {
        this.alamat = alamat;
    }

    public JButton getBatal() {
        return batal;
    }

    public void setBatal(JButton batal) {
        this.batal = batal;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JTextField getNamaLengkap() {
        return namaLengkap;
    }

    public void setNamaLengkap(String namaLengkap) {
        this.namaLengkap.setText(namaLengkap);
    }

    public JTextField getNik() {
        return nik;
    }

    public void setNik(String nik) {
        this.nik.setText(nik);
    }

    public JTextField getNoRekening() {
        return noRekening;
    }

    public void setNoRekening(String noRekening) {
        this.noRekening.setText(noRekening);
    }

    public JTextField getNoTelepon() {
        return noTelepon;
    }

    public void setNoTelepon(String noTelepon) {
        this.noTelepon.setText(noTelepon);
    }

    public JTextField getPendidikanTerakhir() {
        return pendidikanTerakhir;
    }

    public void setPendidikanTerakhir(String pendidikanTerakhir) {
        this.pendidikanTerakhir.setText(pendidikanTerakhir);
    }

    public JTextField getTglLahir() {
        return tglLahir;
    }

    public void setTglLahir(String tglLahir) {
        this.tglLahir.setText(tglLahir);
    }
    
}
