/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author YAHYA
 */
public class viewSemuaPetugas extends javax.swing.JFrame {

    /**
     * Creates new form viewSemuaPetugas
     */
    public viewSemuaPetugas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane1 = new javax.swing.JScrollPane();
        tabelTeller = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelCustomerService = new javax.swing.JTable();
        Batal = new javax.swing.JButton();
        tfHapus = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelTeller.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPane1.setViewportView(tabelTeller);

        getContentPane().add(JScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 442, 273));

        TabelCustomerService.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(TabelCustomerService);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, 273));

        Batal.setText("Batal");
        getContentPane().add(Batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 660, -1, -1));
        getContentPane().add(tfHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 120, 30));

        jLabel3.setText("ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 480, -1, -1));

        hapus.setText("Hapus");
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 690, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/background/36.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 930, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSemuaPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSemuaPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSemuaPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSemuaPetugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSemuaPetugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Batal;
    private javax.swing.JScrollPane JScrollPane1;
    private javax.swing.JTable TabelCustomerService;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelTeller;
    private javax.swing.JTextField tfHapus;
    // End of variables declaration//GEN-END:variables

    public JButton getBatal() {
        return Batal;
    }

    public void setBatal(JButton Batal) {
        this.Batal = Batal;
    }

    public JTable getTabelCustomerService() {
        return TabelCustomerService;
    }

    public void setTabelCustomerService(DefaultTableModel TabelCustomerService) {
        this.TabelCustomerService.setModel(TabelCustomerService);
    }

    public JTable getTabelTeller() {
        return tabelTeller;
    }

    public void setTabelTeller(DefaultTableModel tabelTeller) {
        this.tabelTeller.setModel(tabelTeller);
    }
    public void addActionListener(ActionListener x) {
        Batal.addActionListener(x);
        hapus.addActionListener(x);
    }

    public JButton getHapus() {
        return hapus;
    }

    public void setHapus(JButton hapus) {
        this.hapus = hapus;
    }

    public String getTfHapus() {
        return tfHapus.getText();
    }

    public void setTfHapus(String tfHapus) {
        this.tfHapus.setText(tfHapus);
    }
    
    



}
